//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chadepanela
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista
    {
        public lista()
        {
            this.item = new HashSet<item>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<item> item { get; set; }
    }
}
